<script src="{{asset('public/theme/jobhun/js/jquery.min.js')}}" type="text/javascript"></script>
<script src="{{asset('public/theme/jobhun/js/modernizr.js')}}" type="text/javascript"></script>
<script src="{{asset('public/theme/jobhun/js/script.js')}}" type="text/javascript"></script>
<script src="{{asset('public/theme/jobhun/js/bootstrap.min.js')}}" type="text/javascript"></script>
<script src="{{asset('public/theme/jobhun/js/wow.min.js')}}" type="text/javascript"></script>
<script src="{{asset('public/theme/jobhun/js/slick.min.js')}}" type="text/javascript"></script>
<script src="{{asset('public/theme/jobhun/js/parallax.js')}}" type="text/javascript"></script>
<script src="{{asset('public/theme/jobhun/js/select-chosen.js')}}" type="text/javascript"></script>
<script src="{{asset('public/theme/jobhun/js/jquery.scrollbar.min.js')}}" type="text/javascript"></script>